$axure.loadCurrentPage({
  "url":"登陆界面.html",
  "generationDate":new Date(1492793174560.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d7369366c34841439baa6a05e43d8a5f",
    "type":"Axure:Page",
    "name":"登陆界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bbbcfad66d1b4b42a0f8b66a8e0af640",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":70},
            "size":{
              "width":1500,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05d7abfde5c543f79a12e4dfb12ef7b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":70},
                "size":{
                  "width":1500,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆界面/u0.png"}},
{
          "id":"17b1ab3b1e4d4dbcb8b725fd38cc9a88",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":719.5,
              "y":293},
            "size":{
              "width":321,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c65c0fb3ac6494fab239874d667f7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":719.5,
                  "y":293},
                "size":{
                  "width":321,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0e3da64c7944f10ac8908e114e5fc82",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":657,
              "y":450},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f45cdfb6212145baa433d7a9215b6856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":657,
                  "y":450},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2c514b3747141eb8118b3fcd0c14610",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":780.5,
              "y":453},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8cb4ad66af3f446ea9ef7e9fcf559751",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":657,
              "y":520},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5759e2c66cea4b0e99d20c763937f8db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":657,
                  "y":520},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5855af4e2e34d5db044f25f39bda16e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":523},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"abd34a639efb4219ad94e2dd0efa1d7a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":805,
              "y":650},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cb4fed2cf12148f9a4a8182f6ca1f10e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1470,
              "y":750},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 代理左侧栏提示",
                      "target":{
                        "targetType":"page",
                        "url":"代理左侧栏提示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "bbbcfad66d1b4b42a0f8b66a8e0af640":{
      "scriptId":"u0"},
    "05d7abfde5c543f79a12e4dfb12ef7b4":{
      "scriptId":"u1"},
    "17b1ab3b1e4d4dbcb8b725fd38cc9a88":{
      "scriptId":"u2"},
    "3c65c0fb3ac6494fab239874d667f7f7":{
      "scriptId":"u3"},
    "f0e3da64c7944f10ac8908e114e5fc82":{
      "scriptId":"u4"},
    "f45cdfb6212145baa433d7a9215b6856":{
      "scriptId":"u5"},
    "a2c514b3747141eb8118b3fcd0c14610":{
      "scriptId":"u6"},
    "8cb4ad66af3f446ea9ef7e9fcf559751":{
      "scriptId":"u7"},
    "5759e2c66cea4b0e99d20c763937f8db":{
      "scriptId":"u8"},
    "e5855af4e2e34d5db044f25f39bda16e":{
      "scriptId":"u9"},
    "abd34a639efb4219ad94e2dd0efa1d7a":{
      "scriptId":"u10"},
    "cb4fed2cf12148f9a4a8182f6ca1f10e":{
      "scriptId":"u11"}}});