$axure.loadCurrentPage({
  "url":"代理账号管理.html",
  "generationDate":new Date(1492793176185.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fdfc8d73c0f54913857bd435ead89a17",
    "type":"Axure:Page",
    "name":"代理账号管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3894a265efd240fdac54ddcad3559f2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":28},
            "size":{
              "width":1759,
              "height":882}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8165afcaf1c444238547f0170fb09647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":28},
                "size":{
                  "width":1759,
                  "height":882}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"ce54bb06015d4dd8a00b6892a2324fcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":140},
            "size":{
              "width":200,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"767a78d7d43a4deea9d91534b0753032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":140},
                "size":{
                  "width":200,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u2.png"}},
{
          "id":"5396c89f293d4bcb834d9ef1a2f640ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":140},
            "size":{
              "width":1500,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf2804295f34638985febcec2cfe847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":140},
                "size":{
                  "width":1500,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆界面/u0.png"}},
{
          "id":"22bd987245be48c9b9dc8cd8d76672cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":100},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac5d9f63ba094ff8add3da5f9c9eb36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u8.png"}},
{
          "id":"0ffe248ab5954659ba7a02f1cfad15eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":170},
            "size":{
              "width":54,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c359f4964567496d9a22086785eb11ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":170},
                "size":{
                  "width":54,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d78e63e6e504462be67dfdab90735d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":40},
            "size":{
              "width":1090,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7214ca58e4349629a4c8e83ee33aa37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":40},
                "size":{
                  "width":1090,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u23.png"}},
{
          "id":"b9fa57c3dc3a459b9a85497f7ffa120c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1667,
              "y":49},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00616813630545c8b446a1cdba78ffe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1667,
                  "y":49},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa179984ec22445290708ca0767396cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":90},
            "size":{
              "width":230,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a8b20818f9240c583c53c74a307db4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":90},
                "size":{
                  "width":230,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"84ceff490bf84ed98f094641100db5c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":100},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adca24b664b340e59f2a590b2805382c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":100},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"424d1ece0bdb47c2a3385a07c99e08a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":448,
              "y":99},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2803d662c6244af0a17b879a4095e132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":448,
                  "y":99},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ec91a86d6ab4904838a6e944e5c7fc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":499.999969482422,
              "y":90},
            "size":{
              "width":230,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a65fb7a19ed459096a9934a4129f262",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":499.999969482422,
                  "y":90},
                "size":{
                  "width":230,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"36445ce684014df2929e4fe81ecc2cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":520,
              "y":100},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f05bdf65e240a7b21d6bdf575fcc65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":520,
                  "y":100},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fbca6c417f9431297d3223c9e67a994",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":708,
              "y":99},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e2d4ea047d249f48664e768b53e88e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":708,
                  "y":99},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f20b4e04a3604cc4adcde0dc0983acc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":620,
              "y":172},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58782334a484d6e8c024e47a11c14fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":620,
                  "y":172},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdec22643d7d45eeb40f8e8488cd5691",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":91},
            "size":{
              "width":230,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f8910eeb214342864031dff60f3ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":91},
                "size":{
                  "width":230,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"a8e642d843624dbc82f4f6b29d78ff17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":790,
              "y":101},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f6971b831242b98b6d127ed457c812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":790,
                  "y":101},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bde7bd0566d543adb265599fc34e316a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":978,
              "y":100},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2d21e556f2e4d51b44ec137c17f3678",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":978,
                  "y":100},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a027161d26a44db92061a41cc782f7d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":281},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"c48cdde804074965b8179fab1d454ccb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":329},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"afcec490e93c4f808ea81726e7f8dfa2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":381},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"db23c7ebe55444d283107970839c8c06",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":429},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"4d121863027b4fef953e7e0009ecf8f2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":481},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"6cfb64af4d524394856f8af3e08d219f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":529},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"15e5fc2328654b81bd95dcc0dc335253",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":581},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"23d615e9ba814363aaca3440cb617bc7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":629},
            "size":{
              "width":1465,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/玩家信息查询结果/u70_line.png"}},
{
          "id":"9d482f3507f143b0ae6dda0559e703c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":248.999984741211},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"097159c400c242e8839deb4208011ab5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":248.999984741211},
                "size":{
                  "width":90,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8603550678854b84aa32b4e8ab90dc99",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":502,
              "y":249},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f6bff4b0e5488b9aa022c9baba9e14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":502,
                  "y":249},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8875716065f4e808207db631962f2bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":799,
              "y":249},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3082dc44cdaa4be1984fd1e89e46c03a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":799,
                  "y":249},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f59fdc5f385c48d0adee903d25eb37b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1009,
              "y":249},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"861fc326c0014ed6b684bf1b1111fa74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1009,
                  "y":249},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19bc6b1c649a4a6e9990a93807beb560",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":850,
              "y":170.5},
            "size":{
              "width":127,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3744f1b12d294ecc8521e705855af72c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":850,
                  "y":170.5},
                "size":{
                  "width":127,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"891ee24e2fee4f98a638978ce448cd6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":165.5},
            "size":{
              "width":34,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e47c8f42fcff49429a307144c56412be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":165.5},
                "size":{
                  "width":34,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/玩家信息查询结果/u101.png"}},
{
          "id":"912d498cd7de41b0bbcba72714a248ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1410,
              "y":249},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"722b2ac42bfe4625801a7f7d42182b4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1410,
                  "y":249},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2401b9ba182b4ec59d4a4d3d68b433ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":301},
            "size":{
              "width":61,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"386737c68d244e7f9a119ea2c639e7e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":301},
                "size":{
                  "width":61,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bda1657a35d479eba6b64efc3e3e2fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":502,
              "y":301},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81252500d2da409aaf4ebd12d78065d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":502,
                  "y":301},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6566f9867b034f118b0a0310854e2414",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":819,
              "y":297},
            "size":{
              "width":51,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa55b15442ac4daf9cca11d1fd0375fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":819,
                  "y":297},
                "size":{
                  "width":51,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43d5703375d1444684bad9ec505fa2e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":353},
            "size":{
              "width":61,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04681d5b78d94f8a85ae1cbc4310108a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":353},
                "size":{
                  "width":61,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93e55969245b4be9b2f523a1846d6eaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":502,
              "y":354},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"603a2470cea04fb8acf83b20d74d5e46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":502,
                  "y":354},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcae4e4e8f8147b3aeea60b13255b9d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":401},
            "size":{
              "width":61,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"621012d919cf4368bed63d1be34b90a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":401},
                "size":{
                  "width":61,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfe412d0aa3b4aa4a6740ac723c560a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":502,
              "y":402},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7797fb0637344faa03d507550be5389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":502,
                  "y":402},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a06ebc947ac9412e887e2e07319aa5e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":819,
              "y":349},
            "size":{
              "width":51,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aedf5de0a060490ea709635e43ba9b5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":819,
                  "y":349},
                "size":{
                  "width":51,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4749bff36386481fa7eb08dd9dc7c531",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":819,
              "y":397},
            "size":{
              "width":51,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4d207ef822b449babd2105a50eb3db1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":819,
                  "y":397},
                "size":{
                  "width":51,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b953a2a3bfb64e02bbe9317c650a84ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":978,
              "y":297},
            "size":{
              "width":171,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d02c4b56964c8ea88a4076ec6b42de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":978,
                  "y":297},
                "size":{
                  "width":171,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0c153c8176b4471bde6012651401e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":978,
              "y":349},
            "size":{
              "width":171,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0fe36100d7042beb0f24f6ea682cd7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":978,
                  "y":349},
                "size":{
                  "width":171,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5df4b9b90024299861ec771736ade71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":978,
              "y":397},
            "size":{
              "width":171,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7a67627f7ad422a80bae343a1943929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":978,
                  "y":397},
                "size":{
                  "width":171,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c27d8db1dd9240a498e58c73e680ef90",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1387,
              "y":171},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aabe8ebef42f4197b2e7cde8b44153f3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1617,
              "y":171},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"798642123f4d48d484d2ffdb1afb25f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1268,
              "y":174},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa7b955e5c9f4f7e8bf58466a78dd231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1268,
                  "y":174},
                "size":{
                  "width":90,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6941731abe7a4a5189ea1fab22f83fe8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3154f2c991184483b37b2d369140b43d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":190},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15c7885cdbe747db936850db884e6330",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":230},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7288d9fe1b643459878e7cd31d7a5dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":230},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a80d128b7ab44262b490fd61c3201878",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":278},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd185008cf8b4ac1a9435f8248d25bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":278},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d19a656f33fd4530bc69882273d64b3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":360},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba6142cfbde34ffc9916f18f92f3be3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":360},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b23e6e12cd4241a38e751cea9b133311",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":320},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c87cd723a7749b492221074e8de4011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":320},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"385646f339274ba2a22c065e8780814d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":150},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff387d821b754a49bab5a109d8a61749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":150},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aa889fef99844f6b12e147aed914dfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":450},
            "size":{
              "width":61,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5aea75029c043eebaf50cb0ef26a056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":450},
                "size":{
                  "width":61,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc771782b0ec48b0b78f3fd3b3ad9aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":502,
              "y":451},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6ffb09b1b0a49d39e5a8620d021a2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":502,
                  "y":451},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccd74629e04f485eb7391d892086da6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":819,
              "y":446},
            "size":{
              "width":51,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6552701d875c42f08ff5e1f479d29635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":819,
                  "y":446},
                "size":{
                  "width":51,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc6bf60dbe6a4d1eaa4bd6489a56f81b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":978,
              "y":446},
            "size":{
              "width":171,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b354c2eaff4c2cb40e3952e5ae2edf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":978,
                  "y":446},
                "size":{
                  "width":171,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"395196dcf33a417f87bd4e17e5b72e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":351,
              "y":170},
            "size":{
              "width":61,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c6ae60a32c482e9036853a6f097e97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":351,
                  "y":170},
                "size":{
                  "width":61,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89e01c80ba6e4ee3adb68389d881ed15",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":519,
              "y":171.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f562443345400f863a13dbd0955094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":519,
                  "y":171.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15a9984ce8274b21a033372aa604a31c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1435,
              "y":296},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9626847e9d6a464f94d6d3ede2238a0c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":296},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3330485c3976440ebbff4e741e74c64c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":296},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2b59d2b41b264d75a3b53454be43788d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1435,
              "y":346},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9e1949ae22b745fb842511c0428255d8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":346},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2daed4feeba549b1924746c4c38abf17",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":346},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"083a45865e9642e0883ef7b53a3691bc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1435,
              "y":396},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"99e09765f95848a9b0cd1186c567a94c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":396},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"77ecead267754fab916103d5ea218ef7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":395.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f49a4cc8e5df49abb4fbaaa89f47f9e8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1435,
              "y":446},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9add39b37b964a23b43838b50e6c7db1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1500,
              "y":446},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"51df640ef0b54e13a2378ac97c4fd9ff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":446},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b027c82e85ca485abb6e36aa0a91023e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1309,
              "y":296},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7dd97644ba41481a8371bbf6820b708f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1309,
              "y":346},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6bbfdb4a5d0b4301a8e2bd0e76030462",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1309,
              "y":396},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5034478f40194781a1773517767a3ca1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1309,
              "y":446},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"48d4a765efbe48319bfe833bc798e4f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c6d2dc918f34161874cc492085e179e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":190},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 玩家信息查询",
                      "target":{
                        "targetType":"page",
                        "url":"玩家信息查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05b04d4c894144ba95e13ed28b0b5aad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":230},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"960fce38b33848a89a382d12a6809980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":230},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号操作记录",
                      "target":{
                        "targetType":"page",
                        "url":"账号操作记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2bade9e38c9431e9d71f91dc0cb4b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":278},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2bda4570769444ebe39c43ead1660d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":278},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消费记录",
                      "target":{
                        "targetType":"page",
                        "url":"消费记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0da7d6b61404efcb3beab51371c72c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":320},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3e933bb377f45c1a964ffedf01a842b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":320},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 代理账号管理",
                      "target":{
                        "targetType":"page",
                        "url":"代理账号管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e44c6638fc4e443f8d7f6441d875e94f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":150},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b3aef282b941b5826aa929424516ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":150},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3894a265efd240fdac54ddcad3559f2a":{
      "scriptId":"u0"},
    "8165afcaf1c444238547f0170fb09647":{
      "scriptId":"u1"},
    "ce54bb06015d4dd8a00b6892a2324fcb":{
      "scriptId":"u2"},
    "767a78d7d43a4deea9d91534b0753032":{
      "scriptId":"u3"},
    "5396c89f293d4bcb834d9ef1a2f640ed":{
      "scriptId":"u4"},
    "6cf2804295f34638985febcec2cfe847":{
      "scriptId":"u5"},
    "22bd987245be48c9b9dc8cd8d76672cc":{
      "scriptId":"u6"},
    "ac5d9f63ba094ff8add3da5f9c9eb36a":{
      "scriptId":"u7"},
    "0ffe248ab5954659ba7a02f1cfad15eb":{
      "scriptId":"u8"},
    "c359f4964567496d9a22086785eb11ce":{
      "scriptId":"u9"},
    "1d78e63e6e504462be67dfdab90735d9":{
      "scriptId":"u10"},
    "e7214ca58e4349629a4c8e83ee33aa37":{
      "scriptId":"u11"},
    "b9fa57c3dc3a459b9a85497f7ffa120c":{
      "scriptId":"u12"},
    "00616813630545c8b446a1cdba78ffe1":{
      "scriptId":"u13"},
    "aa179984ec22445290708ca0767396cc":{
      "scriptId":"u14"},
    "6a8b20818f9240c583c53c74a307db4e":{
      "scriptId":"u15"},
    "84ceff490bf84ed98f094641100db5c6":{
      "scriptId":"u16"},
    "adca24b664b340e59f2a590b2805382c":{
      "scriptId":"u17"},
    "424d1ece0bdb47c2a3385a07c99e08a0":{
      "scriptId":"u18"},
    "2803d662c6244af0a17b879a4095e132":{
      "scriptId":"u19"},
    "0ec91a86d6ab4904838a6e944e5c7fc9":{
      "scriptId":"u20"},
    "6a65fb7a19ed459096a9934a4129f262":{
      "scriptId":"u21"},
    "36445ce684014df2929e4fe81ecc2cc1":{
      "scriptId":"u22"},
    "02f05bdf65e240a7b21d6bdf575fcc65":{
      "scriptId":"u23"},
    "5fbca6c417f9431297d3223c9e67a994":{
      "scriptId":"u24"},
    "3e2d4ea047d249f48664e768b53e88e6":{
      "scriptId":"u25"},
    "f20b4e04a3604cc4adcde0dc0983acc0":{
      "scriptId":"u26"},
    "f58782334a484d6e8c024e47a11c14fd":{
      "scriptId":"u27"},
    "cdec22643d7d45eeb40f8e8488cd5691":{
      "scriptId":"u28"},
    "93f8910eeb214342864031dff60f3ed3":{
      "scriptId":"u29"},
    "a8e642d843624dbc82f4f6b29d78ff17":{
      "scriptId":"u30"},
    "44f6971b831242b98b6d127ed457c812":{
      "scriptId":"u31"},
    "bde7bd0566d543adb265599fc34e316a":{
      "scriptId":"u32"},
    "d2d21e556f2e4d51b44ec137c17f3678":{
      "scriptId":"u33"},
    "4a027161d26a44db92061a41cc782f7d":{
      "scriptId":"u34"},
    "c48cdde804074965b8179fab1d454ccb":{
      "scriptId":"u35"},
    "afcec490e93c4f808ea81726e7f8dfa2":{
      "scriptId":"u36"},
    "db23c7ebe55444d283107970839c8c06":{
      "scriptId":"u37"},
    "4d121863027b4fef953e7e0009ecf8f2":{
      "scriptId":"u38"},
    "6cfb64af4d524394856f8af3e08d219f":{
      "scriptId":"u39"},
    "15e5fc2328654b81bd95dcc0dc335253":{
      "scriptId":"u40"},
    "23d615e9ba814363aaca3440cb617bc7":{
      "scriptId":"u41"},
    "9d482f3507f143b0ae6dda0559e703c1":{
      "scriptId":"u42"},
    "097159c400c242e8839deb4208011ab5":{
      "scriptId":"u43"},
    "8603550678854b84aa32b4e8ab90dc99":{
      "scriptId":"u44"},
    "07f6bff4b0e5488b9aa022c9baba9e14":{
      "scriptId":"u45"},
    "e8875716065f4e808207db631962f2bd":{
      "scriptId":"u46"},
    "3082dc44cdaa4be1984fd1e89e46c03a":{
      "scriptId":"u47"},
    "f59fdc5f385c48d0adee903d25eb37b4":{
      "scriptId":"u48"},
    "861fc326c0014ed6b684bf1b1111fa74":{
      "scriptId":"u49"},
    "19bc6b1c649a4a6e9990a93807beb560":{
      "scriptId":"u50"},
    "3744f1b12d294ecc8521e705855af72c":{
      "scriptId":"u51"},
    "891ee24e2fee4f98a638978ce448cd6c":{
      "scriptId":"u52"},
    "e47c8f42fcff49429a307144c56412be":{
      "scriptId":"u53"},
    "912d498cd7de41b0bbcba72714a248ee":{
      "scriptId":"u54"},
    "722b2ac42bfe4625801a7f7d42182b4f":{
      "scriptId":"u55"},
    "2401b9ba182b4ec59d4a4d3d68b433ea":{
      "scriptId":"u56"},
    "386737c68d244e7f9a119ea2c639e7e8":{
      "scriptId":"u57"},
    "6bda1657a35d479eba6b64efc3e3e2fe":{
      "scriptId":"u58"},
    "81252500d2da409aaf4ebd12d78065d9":{
      "scriptId":"u59"},
    "6566f9867b034f118b0a0310854e2414":{
      "scriptId":"u60"},
    "fa55b15442ac4daf9cca11d1fd0375fe":{
      "scriptId":"u61"},
    "43d5703375d1444684bad9ec505fa2e6":{
      "scriptId":"u62"},
    "04681d5b78d94f8a85ae1cbc4310108a":{
      "scriptId":"u63"},
    "93e55969245b4be9b2f523a1846d6eaf":{
      "scriptId":"u64"},
    "603a2470cea04fb8acf83b20d74d5e46":{
      "scriptId":"u65"},
    "fcae4e4e8f8147b3aeea60b13255b9d9":{
      "scriptId":"u66"},
    "621012d919cf4368bed63d1be34b90a7":{
      "scriptId":"u67"},
    "cfe412d0aa3b4aa4a6740ac723c560a0":{
      "scriptId":"u68"},
    "c7797fb0637344faa03d507550be5389":{
      "scriptId":"u69"},
    "a06ebc947ac9412e887e2e07319aa5e5":{
      "scriptId":"u70"},
    "aedf5de0a060490ea709635e43ba9b5b":{
      "scriptId":"u71"},
    "4749bff36386481fa7eb08dd9dc7c531":{
      "scriptId":"u72"},
    "a4d207ef822b449babd2105a50eb3db1":{
      "scriptId":"u73"},
    "b953a2a3bfb64e02bbe9317c650a84ab":{
      "scriptId":"u74"},
    "e5d02c4b56964c8ea88a4076ec6b42de":{
      "scriptId":"u75"},
    "a0c153c8176b4471bde6012651401e16":{
      "scriptId":"u76"},
    "b0fe36100d7042beb0f24f6ea682cd7d":{
      "scriptId":"u77"},
    "b5df4b9b90024299861ec771736ade71":{
      "scriptId":"u78"},
    "d7a67627f7ad422a80bae343a1943929":{
      "scriptId":"u79"},
    "c27d8db1dd9240a498e58c73e680ef90":{
      "scriptId":"u80"},
    "aabe8ebef42f4197b2e7cde8b44153f3":{
      "scriptId":"u81"},
    "798642123f4d48d484d2ffdb1afb25f6":{
      "scriptId":"u82"},
    "aa7b955e5c9f4f7e8bf58466a78dd231":{
      "scriptId":"u83"},
    "6941731abe7a4a5189ea1fab22f83fe8":{
      "scriptId":"u84"},
    "3154f2c991184483b37b2d369140b43d":{
      "scriptId":"u85"},
    "15c7885cdbe747db936850db884e6330":{
      "scriptId":"u86"},
    "f7288d9fe1b643459878e7cd31d7a5dd":{
      "scriptId":"u87"},
    "a80d128b7ab44262b490fd61c3201878":{
      "scriptId":"u88"},
    "cd185008cf8b4ac1a9435f8248d25bff":{
      "scriptId":"u89"},
    "d19a656f33fd4530bc69882273d64b3f":{
      "scriptId":"u90"},
    "ba6142cfbde34ffc9916f18f92f3be3b":{
      "scriptId":"u91"},
    "b23e6e12cd4241a38e751cea9b133311":{
      "scriptId":"u92"},
    "3c87cd723a7749b492221074e8de4011":{
      "scriptId":"u93"},
    "385646f339274ba2a22c065e8780814d":{
      "scriptId":"u94"},
    "ff387d821b754a49bab5a109d8a61749":{
      "scriptId":"u95"},
    "6aa889fef99844f6b12e147aed914dfa":{
      "scriptId":"u96"},
    "d5aea75029c043eebaf50cb0ef26a056":{
      "scriptId":"u97"},
    "fc771782b0ec48b0b78f3fd3b3ad9aa6":{
      "scriptId":"u98"},
    "b6ffb09b1b0a49d39e5a8620d021a2dd":{
      "scriptId":"u99"},
    "ccd74629e04f485eb7391d892086da6a":{
      "scriptId":"u100"},
    "6552701d875c42f08ff5e1f479d29635":{
      "scriptId":"u101"},
    "bc6bf60dbe6a4d1eaa4bd6489a56f81b":{
      "scriptId":"u102"},
    "48b354c2eaff4c2cb40e3952e5ae2edf":{
      "scriptId":"u103"},
    "395196dcf33a417f87bd4e17e5b72e0a":{
      "scriptId":"u104"},
    "11c6ae60a32c482e9036853a6f097e97":{
      "scriptId":"u105"},
    "89e01c80ba6e4ee3adb68389d881ed15":{
      "scriptId":"u106"},
    "55f562443345400f863a13dbd0955094":{
      "scriptId":"u107"},
    "15a9984ce8274b21a033372aa604a31c":{
      "scriptId":"u108"},
    "9626847e9d6a464f94d6d3ede2238a0c":{
      "scriptId":"u109"},
    "3330485c3976440ebbff4e741e74c64c":{
      "scriptId":"u110"},
    "2b59d2b41b264d75a3b53454be43788d":{
      "scriptId":"u111"},
    "9e1949ae22b745fb842511c0428255d8":{
      "scriptId":"u112"},
    "2daed4feeba549b1924746c4c38abf17":{
      "scriptId":"u113"},
    "083a45865e9642e0883ef7b53a3691bc":{
      "scriptId":"u114"},
    "99e09765f95848a9b0cd1186c567a94c":{
      "scriptId":"u115"},
    "77ecead267754fab916103d5ea218ef7":{
      "scriptId":"u116"},
    "f49a4cc8e5df49abb4fbaaa89f47f9e8":{
      "scriptId":"u117"},
    "9add39b37b964a23b43838b50e6c7db1":{
      "scriptId":"u118"},
    "51df640ef0b54e13a2378ac97c4fd9ff":{
      "scriptId":"u119"},
    "b027c82e85ca485abb6e36aa0a91023e":{
      "scriptId":"u120"},
    "7dd97644ba41481a8371bbf6820b708f":{
      "scriptId":"u121"},
    "6bbfdb4a5d0b4301a8e2bd0e76030462":{
      "scriptId":"u122"},
    "5034478f40194781a1773517767a3ca1":{
      "scriptId":"u123"},
    "48d4a765efbe48319bfe833bc798e4f9":{
      "scriptId":"u124"},
    "0c6d2dc918f34161874cc492085e179e":{
      "scriptId":"u125"},
    "05b04d4c894144ba95e13ed28b0b5aad":{
      "scriptId":"u126"},
    "960fce38b33848a89a382d12a6809980":{
      "scriptId":"u127"},
    "f2bade9e38c9431e9d71f91dc0cb4b39":{
      "scriptId":"u128"},
    "a2bda4570769444ebe39c43ead1660d2":{
      "scriptId":"u129"},
    "f0da7d6b61404efcb3beab51371c72c8":{
      "scriptId":"u130"},
    "c3e933bb377f45c1a964ffedf01a842b":{
      "scriptId":"u131"},
    "e44c6638fc4e443f8d7f6441d875e94f":{
      "scriptId":"u132"},
    "d7b3aef282b941b5826aa929424516ba":{
      "scriptId":"u133"}}});