$axure.loadCurrentPage({
  "url":"其他信息.html",
  "generationDate":new Date(1492793175919.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ec89daa39ee94ded961256d7ae9ecb89",
    "type":"Axure:Page",
    "name":"其他信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3894a265efd240fdac54ddcad3559f2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":28},
            "size":{
              "width":1759,
              "height":882}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8165afcaf1c444238547f0170fb09647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":28},
                "size":{
                  "width":1759,
                  "height":882}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"ce54bb06015d4dd8a00b6892a2324fcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":140},
            "size":{
              "width":200,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"767a78d7d43a4deea9d91534b0753032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":140},
                "size":{
                  "width":200,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u2.png"}},
{
          "id":"5396c89f293d4bcb834d9ef1a2f640ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":140},
            "size":{
              "width":1500,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf2804295f34638985febcec2cfe847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":140},
                "size":{
                  "width":1500,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆界面/u0.png"}},
{
          "id":"22bd987245be48c9b9dc8cd8d76672cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":100},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac5d9f63ba094ff8add3da5f9c9eb36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u8.png"}},
{
          "id":"0ffe248ab5954659ba7a02f1cfad15eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":170},
            "size":{
              "width":54,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c359f4964567496d9a22086785eb11ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":170},
                "size":{
                  "width":54,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d78e63e6e504462be67dfdab90735d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":40},
            "size":{
              "width":1090,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7214ca58e4349629a4c8e83ee33aa37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":40},
                "size":{
                  "width":1090,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u23.png"}},
{
          "id":"b9fa57c3dc3a459b9a85497f7ffa120c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1667,
              "y":49},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00616813630545c8b446a1cdba78ffe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1667,
                  "y":49},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa179984ec22445290708ca0767396cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":90},
            "size":{
              "width":230,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a8b20818f9240c583c53c74a307db4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":90},
                "size":{
                  "width":230,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"84ceff490bf84ed98f094641100db5c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":100},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adca24b664b340e59f2a590b2805382c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":100},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"424d1ece0bdb47c2a3385a07c99e08a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":448,
              "y":99},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2803d662c6244af0a17b879a4095e132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":448,
                  "y":99},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ec91a86d6ab4904838a6e944e5c7fc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":499.999969482422,
              "y":90},
            "size":{
              "width":230,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a65fb7a19ed459096a9934a4129f262",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":499.999969482422,
                  "y":90},
                "size":{
                  "width":230,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"36445ce684014df2929e4fe81ecc2cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":520,
              "y":100},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f05bdf65e240a7b21d6bdf575fcc65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":520,
                  "y":100},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fbca6c417f9431297d3223c9e67a994",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":708,
              "y":99},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e2d4ea047d249f48664e768b53e88e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":708,
                  "y":99},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f20b4e04a3604cc4adcde0dc0983acc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":170},
            "size":{
              "width":152,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58782334a484d6e8c024e47a11c14fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":170},
                "size":{
                  "width":152,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdec22643d7d45eeb40f8e8488cd5691",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":91},
            "size":{
              "width":230,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f8910eeb214342864031dff60f3ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":91},
                "size":{
                  "width":230,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"a8e642d843624dbc82f4f6b29d78ff17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":790,
              "y":101},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f6971b831242b98b6d127ed457c812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":790,
                  "y":101},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bde7bd0566d543adb265599fc34e316a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":978,
              "y":100},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2d21e556f2e4d51b44ec137c17f3678",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":978,
                  "y":100},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"682b7ab66bb1489c95ef0e594a7ae110",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":90},
            "size":{
              "width":230,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"038153f9db344b13af5d6ee50e48fb46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1040,
                  "y":90},
                "size":{
                  "width":230,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"e15f80e1c237414babec7393de183d63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1060,
              "y":100},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5ab6a09cf04ff280f09774be707ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1060,
                  "y":100},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71034c788c9d41b8b3427d20e55924f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1248,
              "y":99},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37a40e8acf07404b921361a2fd4482e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1248,
                  "y":99},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6476bc18800445748e632faecccc8781",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1384,
              "y":170},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4b912c2b5bd14b868d4344000a818511",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1614,
              "y":170},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6e84923ba1b248f59ea370fb63d66365",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1265,
              "y":173},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa89608386a4041bf9bb9bd95f71556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1265,
                  "y":173},
                "size":{
                  "width":90,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72afcfff6e9847c380b41e7a5e5ea859",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":248},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3820f4bacc8e424989cd4b6a69dba37f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":248},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf42c76dcf0a467098b494aac6a09b02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":248},
            "size":{
              "width":152,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2896849e098403c969f3e4c227cc8c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":248},
                "size":{
                  "width":152,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dea6ae6224704061b4a983c3a1cb5271",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":298},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2211914f19234d28b78b4a36a5087bb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":298},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"733a4158dad24085b0e124c705a699a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":298},
            "size":{
              "width":81,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"334975e591cc41789d5259dc48215396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":298},
                "size":{
                  "width":81,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"665c2df16113431285fcda6ddd135701",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":350},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d2077f7905413b925123f018c889a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":350},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97537e601e374330a45f5c6944ceb1ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":350},
            "size":{
              "width":81,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"682b44bd025441f38ca741654849cc33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":350},
                "size":{
                  "width":81,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"829b6feeeefb49bd8fd24cc38db06625",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":400},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36f2095796ab4e43b7023c1bea4c6248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":400},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87bd904521c942b1951c7697ce882d91",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":400},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e48f61c4d494e52aafaad0e4d61e548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":400},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab2eaca003ff42e98137fe4182a9a513",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":448},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c46c388a35c54c7096d94e3204f67ad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":448},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ff45c241e444298ab2950050740af13",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":448},
            "size":{
              "width":211,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36a595e335f4184bd967eac685c8d53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":448},
                "size":{
                  "width":211,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdc959a0b6284107b341663a37f526dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":499},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cf70da7bd46439eb846891969a1b8ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":499},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53767bf915fb4b14ad681f800c7e6ffa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":499},
            "size":{
              "width":674,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ef26cda705d45aeb69ccdee3a28bf62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":499},
                "size":{
                  "width":674,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"115cd12d6e4d4c38bcc7ef0f130d7738",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":281,
              "y":548},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5cdc0d7beb04a7ca7901376e1818c50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":281,
                  "y":548},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09d94455d877404d8a6659bebca80071",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":548},
            "size":{
              "width":65,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ebc5ca1377445088b08eb52754b5e0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":548},
                "size":{
                  "width":65,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30251e10585242668278be3228bb6087",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":580},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43cefc4d4d75478a9548ac81fed25b3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":580},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c043fc50277d4c37b5f1a07011a34808",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":612},
            "size":{
              "width":125,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1922a38b6f0e402f942f715148b7d080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":612},
                "size":{
                  "width":125,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abbee4fb22aa4890acaa0dc0a3fe8544",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":644},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfd739e98104460dbf8c6b541d98f80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":644},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdadf7b089e74996a79059b4fc61aa3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":676},
            "size":{
              "width":65,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed696eb50497448b8c6965b21aad37aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":676},
                "size":{
                  "width":65,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"683a6414dc844212b1b347f74b37561e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"385b37487a7d4c52bb0c0ddca84274b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":190},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c0e4c43db634adebac1dcc23e2f297a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":230},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3222b39770f34bfcb4015b69af072cc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":230},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d7f77a1ae4046f4ab0d96bc8064847a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":278},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a985fd62e4be471cac972a0e6a90d994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":278},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de9432faf2404bccbee60b683b04e184",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":360},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97d15a0a224a429ba467bd185f1ca6ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":360},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68e5c136fb414a708c0308cf35311404",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":320},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1af8320da704fe18df0e4e331971eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":320},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aabd95e3ab249b2b0b89316484ecfb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":150},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8990b68f75f43269162845d4af9ec41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":150},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"710ca69adce54b48be34485cdea62e2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9499d0fcbad4433abd199a167ad9d10b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":190},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 玩家信息查询",
                      "target":{
                        "targetType":"page",
                        "url":"玩家信息查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b95a1e8af761490eaebe9119d06a9ec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":230},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07c6d059c5d04fcda12444180f0098de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":230},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号操作记录",
                      "target":{
                        "targetType":"page",
                        "url":"账号操作记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d70a3a258c74903bb64253292916040",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":278},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b571620bce0426fbe09a49cfab9eebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":278},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消费记录",
                      "target":{
                        "targetType":"page",
                        "url":"消费记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9505ced669c245d894f8b4a49a391ebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":320},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72aa1e062d894433a5d5fdd740589848",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":320},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 代理账号管理",
                      "target":{
                        "targetType":"page",
                        "url":"代理账号管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4389b11a28940c19dc35168659b3d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":150},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62862668b03a47bd88ac56b6b23ad14d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":150},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3894a265efd240fdac54ddcad3559f2a":{
      "scriptId":"u0"},
    "8165afcaf1c444238547f0170fb09647":{
      "scriptId":"u1"},
    "ce54bb06015d4dd8a00b6892a2324fcb":{
      "scriptId":"u2"},
    "767a78d7d43a4deea9d91534b0753032":{
      "scriptId":"u3"},
    "5396c89f293d4bcb834d9ef1a2f640ed":{
      "scriptId":"u4"},
    "6cf2804295f34638985febcec2cfe847":{
      "scriptId":"u5"},
    "22bd987245be48c9b9dc8cd8d76672cc":{
      "scriptId":"u6"},
    "ac5d9f63ba094ff8add3da5f9c9eb36a":{
      "scriptId":"u7"},
    "0ffe248ab5954659ba7a02f1cfad15eb":{
      "scriptId":"u8"},
    "c359f4964567496d9a22086785eb11ce":{
      "scriptId":"u9"},
    "1d78e63e6e504462be67dfdab90735d9":{
      "scriptId":"u10"},
    "e7214ca58e4349629a4c8e83ee33aa37":{
      "scriptId":"u11"},
    "b9fa57c3dc3a459b9a85497f7ffa120c":{
      "scriptId":"u12"},
    "00616813630545c8b446a1cdba78ffe1":{
      "scriptId":"u13"},
    "aa179984ec22445290708ca0767396cc":{
      "scriptId":"u14"},
    "6a8b20818f9240c583c53c74a307db4e":{
      "scriptId":"u15"},
    "84ceff490bf84ed98f094641100db5c6":{
      "scriptId":"u16"},
    "adca24b664b340e59f2a590b2805382c":{
      "scriptId":"u17"},
    "424d1ece0bdb47c2a3385a07c99e08a0":{
      "scriptId":"u18"},
    "2803d662c6244af0a17b879a4095e132":{
      "scriptId":"u19"},
    "0ec91a86d6ab4904838a6e944e5c7fc9":{
      "scriptId":"u20"},
    "6a65fb7a19ed459096a9934a4129f262":{
      "scriptId":"u21"},
    "36445ce684014df2929e4fe81ecc2cc1":{
      "scriptId":"u22"},
    "02f05bdf65e240a7b21d6bdf575fcc65":{
      "scriptId":"u23"},
    "5fbca6c417f9431297d3223c9e67a994":{
      "scriptId":"u24"},
    "3e2d4ea047d249f48664e768b53e88e6":{
      "scriptId":"u25"},
    "f20b4e04a3604cc4adcde0dc0983acc0":{
      "scriptId":"u26"},
    "f58782334a484d6e8c024e47a11c14fd":{
      "scriptId":"u27"},
    "cdec22643d7d45eeb40f8e8488cd5691":{
      "scriptId":"u28"},
    "93f8910eeb214342864031dff60f3ed3":{
      "scriptId":"u29"},
    "a8e642d843624dbc82f4f6b29d78ff17":{
      "scriptId":"u30"},
    "44f6971b831242b98b6d127ed457c812":{
      "scriptId":"u31"},
    "bde7bd0566d543adb265599fc34e316a":{
      "scriptId":"u32"},
    "d2d21e556f2e4d51b44ec137c17f3678":{
      "scriptId":"u33"},
    "682b7ab66bb1489c95ef0e594a7ae110":{
      "scriptId":"u34"},
    "038153f9db344b13af5d6ee50e48fb46":{
      "scriptId":"u35"},
    "e15f80e1c237414babec7393de183d63":{
      "scriptId":"u36"},
    "9d5ab6a09cf04ff280f09774be707ce3":{
      "scriptId":"u37"},
    "71034c788c9d41b8b3427d20e55924f1":{
      "scriptId":"u38"},
    "37a40e8acf07404b921361a2fd4482e8":{
      "scriptId":"u39"},
    "6476bc18800445748e632faecccc8781":{
      "scriptId":"u40"},
    "4b912c2b5bd14b868d4344000a818511":{
      "scriptId":"u41"},
    "6e84923ba1b248f59ea370fb63d66365":{
      "scriptId":"u42"},
    "7aa89608386a4041bf9bb9bd95f71556":{
      "scriptId":"u43"},
    "72afcfff6e9847c380b41e7a5e5ea859":{
      "scriptId":"u44"},
    "3820f4bacc8e424989cd4b6a69dba37f":{
      "scriptId":"u45"},
    "cf42c76dcf0a467098b494aac6a09b02":{
      "scriptId":"u46"},
    "e2896849e098403c969f3e4c227cc8c2":{
      "scriptId":"u47"},
    "dea6ae6224704061b4a983c3a1cb5271":{
      "scriptId":"u48"},
    "2211914f19234d28b78b4a36a5087bb4":{
      "scriptId":"u49"},
    "733a4158dad24085b0e124c705a699a3":{
      "scriptId":"u50"},
    "334975e591cc41789d5259dc48215396":{
      "scriptId":"u51"},
    "665c2df16113431285fcda6ddd135701":{
      "scriptId":"u52"},
    "46d2077f7905413b925123f018c889a7":{
      "scriptId":"u53"},
    "97537e601e374330a45f5c6944ceb1ef":{
      "scriptId":"u54"},
    "682b44bd025441f38ca741654849cc33":{
      "scriptId":"u55"},
    "829b6feeeefb49bd8fd24cc38db06625":{
      "scriptId":"u56"},
    "36f2095796ab4e43b7023c1bea4c6248":{
      "scriptId":"u57"},
    "87bd904521c942b1951c7697ce882d91":{
      "scriptId":"u58"},
    "5e48f61c4d494e52aafaad0e4d61e548":{
      "scriptId":"u59"},
    "ab2eaca003ff42e98137fe4182a9a513":{
      "scriptId":"u60"},
    "c46c388a35c54c7096d94e3204f67ad0":{
      "scriptId":"u61"},
    "5ff45c241e444298ab2950050740af13":{
      "scriptId":"u62"},
    "d36a595e335f4184bd967eac685c8d53":{
      "scriptId":"u63"},
    "cdc959a0b6284107b341663a37f526dc":{
      "scriptId":"u64"},
    "2cf70da7bd46439eb846891969a1b8ad":{
      "scriptId":"u65"},
    "53767bf915fb4b14ad681f800c7e6ffa":{
      "scriptId":"u66"},
    "4ef26cda705d45aeb69ccdee3a28bf62":{
      "scriptId":"u67"},
    "115cd12d6e4d4c38bcc7ef0f130d7738":{
      "scriptId":"u68"},
    "c5cdc0d7beb04a7ca7901376e1818c50":{
      "scriptId":"u69"},
    "09d94455d877404d8a6659bebca80071":{
      "scriptId":"u70"},
    "0ebc5ca1377445088b08eb52754b5e0c":{
      "scriptId":"u71"},
    "30251e10585242668278be3228bb6087":{
      "scriptId":"u72"},
    "43cefc4d4d75478a9548ac81fed25b3e":{
      "scriptId":"u73"},
    "c043fc50277d4c37b5f1a07011a34808":{
      "scriptId":"u74"},
    "1922a38b6f0e402f942f715148b7d080":{
      "scriptId":"u75"},
    "abbee4fb22aa4890acaa0dc0a3fe8544":{
      "scriptId":"u76"},
    "dfd739e98104460dbf8c6b541d98f80a":{
      "scriptId":"u77"},
    "cdadf7b089e74996a79059b4fc61aa3e":{
      "scriptId":"u78"},
    "ed696eb50497448b8c6965b21aad37aa":{
      "scriptId":"u79"},
    "683a6414dc844212b1b347f74b37561e":{
      "scriptId":"u80"},
    "385b37487a7d4c52bb0c0ddca84274b3":{
      "scriptId":"u81"},
    "9c0e4c43db634adebac1dcc23e2f297a":{
      "scriptId":"u82"},
    "3222b39770f34bfcb4015b69af072cc1":{
      "scriptId":"u83"},
    "6d7f77a1ae4046f4ab0d96bc8064847a":{
      "scriptId":"u84"},
    "a985fd62e4be471cac972a0e6a90d994":{
      "scriptId":"u85"},
    "de9432faf2404bccbee60b683b04e184":{
      "scriptId":"u86"},
    "97d15a0a224a429ba467bd185f1ca6ac":{
      "scriptId":"u87"},
    "68e5c136fb414a708c0308cf35311404":{
      "scriptId":"u88"},
    "e1af8320da704fe18df0e4e331971eb3":{
      "scriptId":"u89"},
    "3aabd95e3ab249b2b0b89316484ecfb4":{
      "scriptId":"u90"},
    "f8990b68f75f43269162845d4af9ec41":{
      "scriptId":"u91"},
    "710ca69adce54b48be34485cdea62e2f":{
      "scriptId":"u92"},
    "9499d0fcbad4433abd199a167ad9d10b":{
      "scriptId":"u93"},
    "b95a1e8af761490eaebe9119d06a9ec1":{
      "scriptId":"u94"},
    "07c6d059c5d04fcda12444180f0098de":{
      "scriptId":"u95"},
    "2d70a3a258c74903bb64253292916040":{
      "scriptId":"u96"},
    "2b571620bce0426fbe09a49cfab9eebb":{
      "scriptId":"u97"},
    "9505ced669c245d894f8b4a49a391ebe":{
      "scriptId":"u98"},
    "72aa1e062d894433a5d5fdd740589848":{
      "scriptId":"u99"},
    "d4389b11a28940c19dc35168659b3d6d":{
      "scriptId":"u100"},
    "62862668b03a47bd88ac56b6b23ad14d":{
      "scriptId":"u101"}}});