$axure.loadCurrentPage({
  "url":"账号操作记录.html",
  "generationDate":new Date(1492793176974.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"769db697425747bebe14ecc2e607b54a",
    "type":"Axure:Page",
    "name":"账号操作记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3894a265efd240fdac54ddcad3559f2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":28},
            "size":{
              "width":1759,
              "height":882}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8165afcaf1c444238547f0170fb09647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":28},
                "size":{
                  "width":1759,
                  "height":882}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"ce54bb06015d4dd8a00b6892a2324fcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":140},
            "size":{
              "width":200,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"767a78d7d43a4deea9d91534b0753032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":140},
                "size":{
                  "width":200,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u2.png"}},
{
          "id":"5396c89f293d4bcb834d9ef1a2f640ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":140},
            "size":{
              "width":1500,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf2804295f34638985febcec2cfe847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":140},
                "size":{
                  "width":1500,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆界面/u0.png"}},
{
          "id":"22bd987245be48c9b9dc8cd8d76672cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":100},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac5d9f63ba094ff8add3da5f9c9eb36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u8.png"}},
{
          "id":"1d78e63e6e504462be67dfdab90735d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":40},
            "size":{
              "width":1090,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7214ca58e4349629a4c8e83ee33aa37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":40},
                "size":{
                  "width":1090,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u23.png"}},
{
          "id":"b9fa57c3dc3a459b9a85497f7ffa120c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1667,
              "y":49},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00616813630545c8b446a1cdba78ffe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1667,
                  "y":49},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c27d8db1dd9240a498e58c73e680ef90",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1387,
              "y":171},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aabe8ebef42f4197b2e7cde8b44153f3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1617,
              "y":171},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"798642123f4d48d484d2ffdb1afb25f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1268,
              "y":174},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa7b955e5c9f4f7e8bf58466a78dd231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1268,
                  "y":174},
                "size":{
                  "width":90,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9af54de411314f43a57625f8ff98d855",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":640},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e4bf1a11a2417fb32c268e8c838384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":640},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23f980fa6b6f4e3994b5411571af5604",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":640},
            "size":{
              "width":41,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9946a68c58544678007e4ec5dcd172d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":640},
                "size":{
                  "width":41,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ba9c0a3c16b4e819f8387b206bea258",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":260,
              "y":680},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8255c288bf9d49d08dc94ab1219986b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":260,
                  "y":680},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d635e72ddc5f43c6b08815942ad4570d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":410,
              "y":680},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e32330e06b6463c808ef80fa4cd56bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":410,
                  "y":680},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ceab7ef78ccd49f1a4d9817f3ddc8041",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":269,
              "y":164},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea87a8ab167a466292ea2b942b7105c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":269,
                  "y":164},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"319535f508c14463801ab957d8e9a5fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605b93703f2e45b4ba75cec0278e2b7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":190},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 玩家信息查询",
                      "target":{
                        "targetType":"page",
                        "url":"玩家信息查询.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c026a9e54cc048deaea27c53ff7b5a80",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":230},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b6d808fb4a41f1a8b8837ab430f923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":230},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号操作记录",
                      "target":{
                        "targetType":"page",
                        "url":"账号操作记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d17b6c89c05542cb9327991b48d422e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":40,
              "y":278},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de568aa3c36840a3930ba429006e82ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":40,
                  "y":278},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消费记录",
                      "target":{
                        "targetType":"page",
                        "url":"消费记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3c23ce0a14642feb83f84218276330a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":320},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a1947133f4640f98d0556badba41e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":320},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 代理账号管理",
                      "target":{
                        "targetType":"page",
                        "url":"代理账号管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b8025b6763d4a349bcbe60585b4d646",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":150},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcdf7ae7b6b6401fa7894dc0c51ed37f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":150},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3894a265efd240fdac54ddcad3559f2a":{
      "scriptId":"u0"},
    "8165afcaf1c444238547f0170fb09647":{
      "scriptId":"u1"},
    "ce54bb06015d4dd8a00b6892a2324fcb":{
      "scriptId":"u2"},
    "767a78d7d43a4deea9d91534b0753032":{
      "scriptId":"u3"},
    "5396c89f293d4bcb834d9ef1a2f640ed":{
      "scriptId":"u4"},
    "6cf2804295f34638985febcec2cfe847":{
      "scriptId":"u5"},
    "22bd987245be48c9b9dc8cd8d76672cc":{
      "scriptId":"u6"},
    "ac5d9f63ba094ff8add3da5f9c9eb36a":{
      "scriptId":"u7"},
    "1d78e63e6e504462be67dfdab90735d9":{
      "scriptId":"u8"},
    "e7214ca58e4349629a4c8e83ee33aa37":{
      "scriptId":"u9"},
    "b9fa57c3dc3a459b9a85497f7ffa120c":{
      "scriptId":"u10"},
    "00616813630545c8b446a1cdba78ffe1":{
      "scriptId":"u11"},
    "c27d8db1dd9240a498e58c73e680ef90":{
      "scriptId":"u12"},
    "aabe8ebef42f4197b2e7cde8b44153f3":{
      "scriptId":"u13"},
    "798642123f4d48d484d2ffdb1afb25f6":{
      "scriptId":"u14"},
    "aa7b955e5c9f4f7e8bf58466a78dd231":{
      "scriptId":"u15"},
    "9af54de411314f43a57625f8ff98d855":{
      "scriptId":"u16"},
    "45e4bf1a11a2417fb32c268e8c838384":{
      "scriptId":"u17"},
    "23f980fa6b6f4e3994b5411571af5604":{
      "scriptId":"u18"},
    "e9946a68c58544678007e4ec5dcd172d":{
      "scriptId":"u19"},
    "0ba9c0a3c16b4e819f8387b206bea258":{
      "scriptId":"u20"},
    "8255c288bf9d49d08dc94ab1219986b7":{
      "scriptId":"u21"},
    "d635e72ddc5f43c6b08815942ad4570d":{
      "scriptId":"u22"},
    "2e32330e06b6463c808ef80fa4cd56bf":{
      "scriptId":"u23"},
    "ceab7ef78ccd49f1a4d9817f3ddc8041":{
      "scriptId":"u24"},
    "ea87a8ab167a466292ea2b942b7105c5":{
      "scriptId":"u25"},
    "319535f508c14463801ab957d8e9a5fd":{
      "scriptId":"u26"},
    "605b93703f2e45b4ba75cec0278e2b7f":{
      "scriptId":"u27"},
    "c026a9e54cc048deaea27c53ff7b5a80":{
      "scriptId":"u28"},
    "41b6d808fb4a41f1a8b8837ab430f923":{
      "scriptId":"u29"},
    "d17b6c89c05542cb9327991b48d422e5":{
      "scriptId":"u30"},
    "de568aa3c36840a3930ba429006e82ca":{
      "scriptId":"u31"},
    "c3c23ce0a14642feb83f84218276330a":{
      "scriptId":"u32"},
    "7a1947133f4640f98d0556badba41e3e":{
      "scriptId":"u33"},
    "4b8025b6763d4a349bcbe60585b4d646":{
      "scriptId":"u34"},
    "fcdf7ae7b6b6401fa7894dc0c51ed37f":{
      "scriptId":"u35"}}});